### ISSUE TITLE
Function missing

### ISSUE THREAD

**Issue by wardjm** [trneedham/Weighted-Euler-Curve-Transform#1]
It looks like the weighted_euler_curve function doesn't exist in this repository.

**Comment by trneedham** [comment]
Whoops, I think it was renamed to something specific to an experiment at some point. It should be fixed now. Thanks for pointing this out!

**Comment by wardjm** [comment]
Thanks! It was pretty obvious which function it should be, but I wasn't sure if there were other changes other than the name.
